"""Try migration 2

Revision ID: efb3b9ad52e9
Revises: fcd59705578f
Create Date: 2024-04-12 13:12:05.684031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb3b9ad52e9'
down_revision: Union[str, None] = 'fcd59705578f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'file_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
